/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import classes.Cliente;
import classes.PessoaFisica;
import classes.PessoaJuridica;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author matheus.souza
 */
public class TelaCadastroClientes extends javax.swing.JDialog {

    private Cliente clienteTemp = null;
    private boolean alterar = false;

    /**
     * Creates new form TelaCadastroPessoas
     */
    public TelaCadastroClientes(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public Cliente execute() {
        this.setVisible(true);
        return this.clienteTemp;
    }

    public Cliente execute(Cliente c) {
        SimpleDateFormat f = new SimpleDateFormat("##/##/####");

        this.clienteTemp = c;
        this.alterar = true;

        txtNome.setText(c.getNome());
        txtEndereco.setText(c.getEndereco());

        if (c instanceof PessoaFisica) {
            
            txtCNH.setText(c.getCNHouCNHResp());
            txtCpfCnpj.setText(c.getCPFouCNPJ());
            txtDataDesc.setText(f.format(((PessoaFisica) c).getDtNascimento()));
            
        } else if (c instanceof PessoaJuridica) {
            
            txtCNH.setText(c.getCNHouCNHResp());
            txtCpfCnpj.setText(c.getCPFouCNPJ());
            txtDataDesc.setText(Float.toString(((PessoaJuridica) c).getDescontoLocacao()));

        }

        this.setVisible(true);
        return this.clienteTemp;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroup = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        rdBtnCpf = new javax.swing.JRadioButton();
        rdBtnCnpj = new javax.swing.JRadioButton();
        lblCpfCnpj = new javax.swing.JLabel();
        lblDataDesc = new javax.swing.JLabel();
        txtDataDesc = new javax.swing.JFormattedTextField();
        txtCNH = new javax.swing.JTextField();
        txtEndereco = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        btnGravarCliente = new javax.swing.JButton();
        btnCancelarCliente = new javax.swing.JButton();
        txtCpfCnpj = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel1.setText("Nome:");

        jLabel2.setText("Endereço:");

        jLabel3.setText("CNH:");

        btnGroup.add(rdBtnCpf);
        rdBtnCpf.setText("CPF");
        rdBtnCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdBtnCpfActionPerformed(evt);
            }
        });

        btnGroup.add(rdBtnCnpj);
        rdBtnCnpj.setText("CNPJ");
        rdBtnCnpj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdBtnCnpjActionPerformed(evt);
            }
        });

        lblCpfCnpj.setText("CPF:");

        lblDataDesc.setText("Nascimento:");

        try {
            txtDataDesc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtDataDesc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDataDescActionPerformed(evt);
            }
        });

        btnGravarCliente.setText("Gravar");
        btnGravarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGravarClienteActionPerformed(evt);
            }
        });

        btnCancelarCliente.setText("Cancelar");
        btnCancelarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rdBtnCpf)
                                    .addComponent(rdBtnCnpj))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblCpfCnpj)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCpfCnpj))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtCNH, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblDataDesc)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtDataDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtEndereco)
                                    .addComponent(txtNome))))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnGravarCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCancelarCliente)
                        .addGap(46, 46, 46))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtCNH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDataDesc)
                    .addComponent(txtDataDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rdBtnCpf)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rdBtnCnpj))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCpfCnpj)
                            .addComponent(txtCpfCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGravarCliente)
                    .addComponent(btnCancelarCliente))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtDataDescActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDataDescActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDataDescActionPerformed

    private void btnGravarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGravarClienteActionPerformed
        // TODO add your handling code here:
        try {
            SimpleDateFormat f = new SimpleDateFormat("dd/MM/yyyy");
            Cliente cliente = null;

            if (rdBtnCpf.isSelected()) {

                if (this.alterar == true) {
                    cliente = this.clienteTemp;
                } else {
                    cliente = new PessoaFisica();
                }

                ((PessoaFisica) cliente).setCpf(txtCpfCnpj.getText());
                ((PessoaFisica) cliente).setCnh(txtCNH.getText());
                ((PessoaFisica) cliente).setDtNascimento(f.parse(txtDataDesc.getText()));
            } else if (rdBtnCnpj.isSelected()) {

                if (this.alterar == true) {
                    cliente = this.clienteTemp;
                } else {
                    cliente = new PessoaJuridica();
                }
                ((PessoaJuridica) cliente).setCnpj(txtCpfCnpj.getText());
                ((PessoaJuridica) cliente).setCnhResponsavel(txtCpfCnpj.getText());
                ((PessoaJuridica) cliente).setDescontoLocacao(Float.parseFloat(txtDataDesc.getText()));

            }

            cliente.setNome(txtNome.getText());
            cliente.setEndereco(txtEndereco.getText());

            this.clienteTemp = cliente;
            this.setVisible(false);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this,
                    "Não foi possível gravar o cliente. \n\n" + ex.getMessage(),
                    "Erro",
                    JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnGravarClienteActionPerformed

    private void rdBtnCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdBtnCpfActionPerformed
        // TODO add your handling code here:
        try {
            if (rdBtnCpf.isSelected()) {
                lblCpfCnpj.setText("CPF");
                lblDataDesc.setText("Nascimento:");

                MaskFormatter maskCPFCNPJ = new MaskFormatter("###.###.###-##");
                MaskFormatter maskDataDesc = new MaskFormatter("##/##/####");

                DefaultFormatterFactory dffCPFCNPJ = new DefaultFormatterFactory(maskCPFCNPJ);
                DefaultFormatterFactory dffDataDesc = new DefaultFormatterFactory(maskDataDesc);

                txtCpfCnpj.setFormatterFactory(dffCPFCNPJ);
                txtDataDesc.setFormatterFactory(dffDataDesc);
            }
        } catch (Exception ex) {
        }
    }//GEN-LAST:event_rdBtnCpfActionPerformed

    private void rdBtnCnpjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdBtnCnpjActionPerformed
        // TODO add your handling code here:
        try {
            if (rdBtnCnpj.isSelected()) {
                lblCpfCnpj.setText("CNPJ");
                lblDataDesc.setText("Desconto(%):");

                MaskFormatter maskCPFCNPJ = new MaskFormatter("##.###.###/####-##");
                MaskFormatter maskDataDesc = new MaskFormatter("##");

                DefaultFormatterFactory dffCPFCNPJ = new DefaultFormatterFactory(maskCPFCNPJ);
                DefaultFormatterFactory dffDataDesc = new DefaultFormatterFactory(maskDataDesc);

                txtCpfCnpj.setFormatterFactory(dffCPFCNPJ);
                txtDataDesc.setFormatterFactory(dffDataDesc);
            }
        } catch (Exception ex) {
        }
    }//GEN-LAST:event_rdBtnCnpjActionPerformed

    private void btnCancelarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarClienteActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        this.clienteTemp = null;
    }//GEN-LAST:event_btnCancelarClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaCadastroClientes dialog = new TelaCadastroClientes(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarCliente;
    private javax.swing.JButton btnGravarCliente;
    private javax.swing.ButtonGroup btnGroup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblCpfCnpj;
    private javax.swing.JLabel lblDataDesc;
    private javax.swing.JRadioButton rdBtnCnpj;
    private javax.swing.JRadioButton rdBtnCpf;
    private javax.swing.JTextField txtCNH;
    private javax.swing.JFormattedTextField txtCpfCnpj;
    private javax.swing.JFormattedTextField txtDataDesc;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
