/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import classes.Carro;
import classes.Cliente;
import classes.PessoaFisica;
import classes.PessoaJuridica;
import dados.CarroDados;
import dados.ClienteDados;
import java.util.List;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author matheus.souza
 */
public class TelaPrincipal extends javax.swing.JFrame {

    private Carro carroTemp = null;

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblCarros = new javax.swing.JTable();
        btnNovoCarro = new javax.swing.JButton();
        btnAlterarCarro1 = new javax.swing.JButton();
        btnExcluirCarro2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtBuscarCarro = new javax.swing.JTextField();
        btnBuscarCarro = new javax.swing.JButton();
        btnLimparBuscarCarro = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnNovoCliente = new javax.swing.JButton();
        btnAlterarCliente = new javax.swing.JButton();
        btnExcluirCliente = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblClientes = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        btnSairArquivo = new javax.swing.JMenuItem();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TelaPrincipal");
        setResizable(false);

        tblCarros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Placa", "Marca", "Modelo", "Ano", "Valor da Diária"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblCarros);

        btnNovoCarro.setText("Novo");
        btnNovoCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoCarroActionPerformed(evt);
            }
        });

        btnAlterarCarro1.setText("Alterar");
        btnAlterarCarro1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarCarro1ActionPerformed(evt);
            }
        });

        btnExcluirCarro2.setText("Excluir");
        btnExcluirCarro2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirCarro2ActionPerformed(evt);
            }
        });

        jLabel1.setText("Buscar pela placa: ");

        btnBuscarCarro.setText("Buscar");
        btnBuscarCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarCarroActionPerformed(evt);
            }
        });

        btnLimparBuscarCarro.setText("Limpar busca");
        btnLimparBuscarCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparBuscarCarroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBuscarCarro, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscarCarro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLimparBuscarCarro, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnNovoCarro, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAlterarCarro1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnExcluirCarro2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscarCarro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarCarro)
                    .addComponent(jLabel1)
                    .addComponent(btnLimparBuscarCarro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNovoCarro)
                    .addComponent(btnAlterarCarro1)
                    .addComponent(btnExcluirCarro2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Carros", jPanel1);

        btnNovoCliente.setText("Novo");
        btnNovoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoClienteActionPerformed(evt);
            }
        });

        btnAlterarCliente.setText("Alterar");
        btnAlterarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarClienteActionPerformed(evt);
            }
        });

        btnExcluirCliente.setText("Excluir");
        btnExcluirCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirClienteActionPerformed(evt);
            }
        });

        tblClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Endereço", "CPF ou CNPJ", "CNH", "DtNascimento", "Desconto"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblClientes);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnNovoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAlterarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnExcluirCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 415, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNovoCliente)
                    .addComponent(btnAlterarCliente)
                    .addComponent(btnExcluirCliente))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Clientes", jPanel2);

        jMenu1.setText("Arquivo");

        btnSairArquivo.setText("Sair");
        btnSairArquivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairArquivoActionPerformed(evt);
            }
        });
        jMenu1.add(btnSairArquivo);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSairArquivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairArquivoActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSairArquivoActionPerformed

    private void btnNovoCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoCarroActionPerformed
        TelaCadastroCarros telaCadastroCarros = new TelaCadastroCarros(this, true);

        Carro c = telaCadastroCarros.execute();

        CarroDados.lstCarros.add(c);
        this.atualizaTabelaCarros(CarroDados.lstCarros);
    }//GEN-LAST:event_btnNovoCarroActionPerformed

    private void btnAlterarCarro1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarCarro1ActionPerformed
        try {
            if (CarroDados.lstCarros.size() > 0) {
                if (tblCarros.getSelectedRow() != -1) {
                    Carro c = CarroDados.lstCarros.get(tblCarros.getSelectedRow());
                    if (c != null) {

                        if (JOptionPane.showConfirmDialog(this,
                                "Deseja alterar " + c.getPlaca() + "?",
                                "Carros",
                                JOptionPane.YES_NO_OPTION,
                                JOptionPane.QUESTION_MESSAGE) == JOptionPane.YES_OPTION) {

                            TelaCadastroCarros telaCadastroCarros = new TelaCadastroCarros(this, true);
                            telaCadastroCarros.execute(c);
                            this.atualizaTabelaCarros(CarroDados.lstCarros);
                        }
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Não há itens selecionados",
                            "Atenção",
                            JOptionPane.WARNING_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Não há veículos na lista!",
                        "Atenção",
                        JOptionPane.WARNING_MESSAGE);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this,
                    "Não foi possível alterar o carro.\n\n" + ex.getMessage(),
                    "Erro",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAlterarCarro1ActionPerformed

    private void btnExcluirCarro2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirCarro2ActionPerformed
        try {

            if (CarroDados.lstCarros.size() > 0) {

                String placa = tblCarros.getValueAt(tblCarros.getSelectedRow(), 0).toString();
                Carro c = CarroDados.obterCarroPorPlaca(placa, CarroDados.lstCarros);
                if (c != null) {

                    if (JOptionPane.showConfirmDialog(this,
                            "Deseja Excluir " + c.getPlaca() + "?",
                            "Carros",
                            JOptionPane.YES_NO_OPTION,
                            JOptionPane.QUESTION_MESSAGE) == JOptionPane.YES_OPTION) {

                        //TelaCadastroCarros telaCadastroCarros = new TelaCadastroCarros(this, true);
                        CarroDados.lstCarros.remove(c);

                        this.atualizaTabelaCarros(CarroDados.lstCarros);
                    }
                }
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this,
                    "Não foi possível excluir o carro.\n\n" + ex.getMessage(),
                    "Erro",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnExcluirCarro2ActionPerformed

    private void btnBuscarCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarCarroActionPerformed

        if (!txtBuscarCarro.getText().equals("")) {
            Carro c = CarroDados.obterCarroPorPlaca(txtBuscarCarro.getText().trim(), CarroDados.lstCarros);
            buscaTabelaCarros(c);
        } else {
            atualizaTabelaCarros(CarroDados.lstCarros);
        }
    }//GEN-LAST:event_btnBuscarCarroActionPerformed

    private void btnLimparBuscarCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparBuscarCarroActionPerformed
        // TODO add your handling code here:
        atualizaTabelaCarros(CarroDados.lstCarros);
    }//GEN-LAST:event_btnLimparBuscarCarroActionPerformed

    private void btnNovoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoClienteActionPerformed
        // TODO add your handling code here:
        TelaCadastroClientes telaCadastroClientes = new TelaCadastroClientes(this, true);

        Cliente c = telaCadastroClientes.execute();

        ClienteDados.lstClientes.add(c);
        this.atualizaTabelaClientes(ClienteDados.lstClientes);
    }//GEN-LAST:event_btnNovoClienteActionPerformed

    private void btnAlterarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarClienteActionPerformed
        // TODO add your handling code here:
        try {
            if (ClienteDados.lstClientes.size() > 0) {
                if (tblClientes.getSelectedRow() != -1) {
                    Cliente c = ClienteDados.lstClientes.get(tblClientes.getSelectedRow());
                    if (c != null) {

                        if (JOptionPane.showConfirmDialog(this,
                                "Deseja alterar " + c.getNome() + "?",
                                "Clientes",
                                JOptionPane.YES_NO_OPTION,
                                JOptionPane.QUESTION_MESSAGE) == JOptionPane.YES_OPTION) {

                            TelaCadastroClientes telaCadastroClientes = new TelaCadastroClientes(this, true);
                            telaCadastroClientes.execute(c);
                            this.atualizaTabelaClientes(ClienteDados.lstClientes);
                        }
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Não há itens selecionados",
                            "Atenção",
                            JOptionPane.WARNING_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Não há clientes na lista!",
                        "Atenção",
                        JOptionPane.WARNING_MESSAGE);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this,
                    "Não foi possível alterar o cliente.\n\n" + ex.getMessage(),
                    "Erro",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAlterarClienteActionPerformed

    private void btnExcluirClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirClienteActionPerformed
        // TODO add your handling code here:
        try {

            if (ClienteDados.lstClientes.size() > 0) {

                String nome = tblClientes.getValueAt(tblClientes.getSelectedRow(), 0).toString();
                Cliente c = ClienteDados.obterClientePorNome(nome, ClienteDados.lstClientes);
                if (c != null) {

                    if (JOptionPane.showConfirmDialog(this,
                            "Deseja Excluir " + c.getNome() + "?",
                            "Clietes",
                            JOptionPane.YES_NO_OPTION,
                            JOptionPane.QUESTION_MESSAGE) == JOptionPane.YES_OPTION) {

                        //TelaCadastroCarros telaCadastroCarros = new TelaCadastroCarros(this, true);
                        ClienteDados.lstClientes.remove(c);

                        this.atualizaTabelaClientes(ClienteDados.lstClientes);
                    }
                }
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this,
                    "Não foi possível excluir o carro.\n\n" + ex.getMessage(),
                    "Erro",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnExcluirClienteActionPerformed

    private void atualizaTabelaCarros(List<Carro> tabelaCarros) {
        try {
            DefaultTableModel modelo = (DefaultTableModel) tblCarros.getModel();
            modelo.getDataVector().removeAllElements();

            for (Carro carros : tabelaCarros) {
                Vector v = new Vector();
                v.add(carros.getPlaca());
                v.add(carros.getMarca());
                v.add(carros.getModelo());
                v.add(carros.getAno());
                v.add(carros.getValorDiariaLocacao());

                modelo.addRow(v);
            }

            tblCarros.repaint();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this,
                    "Não foi possível carregar o novo carro.\n\n" + ex.getMessage(),
                    "Erro",
                    JOptionPane.ERROR_MESSAGE);
        }
    }

    private void buscaTabelaCarros(Carro carro) {
        try {
            if (!CarroDados.lstCarros.isEmpty()) {
                if (carro != null) {
                    DefaultTableModel modelo = (DefaultTableModel) tblCarros.getModel();
                    modelo.getDataVector().removeAllElements();

                    Vector v = new Vector();
                    v.add(carro.getPlaca());
                    v.add(carro.getMarca());
                    v.add(carro.getModelo());
                    v.add(carro.getAno());
                    v.add(carro.getValorDiariaLocacao());

                    modelo.addRow(v);

                    tblCarros.repaint();
                } else {
                    JOptionPane.showMessageDialog(this, "Nenhum veículo foi encontrado!",
                            "Atenção",
                            JOptionPane.WARNING_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Não há veículos na lista!",
                        "Atenção",
                        JOptionPane.WARNING_MESSAGE);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this,
                    "Não foi possível buscar o carro.\n\n" + ex.getMessage(),
                    "Erro",
                    JOptionPane.ERROR_MESSAGE);
        }
    }

    private void atualizaTabelaClientes(List<Cliente> tabelaClientes) {
        try {
            DefaultTableModel modelo = (DefaultTableModel) tblClientes.getModel();
            modelo.getDataVector().removeAllElements();

            for (Cliente clientes : tabelaClientes) {
                Vector v = new Vector();
                v.add(clientes.getNome());
                v.add(clientes.getEndereco());
                v.add(clientes.getCPFouCNPJ());
                v.add(clientes.getCNHouCNHResp());

                if (clientes instanceof PessoaFisica) {
                    v.add(((PessoaFisica) clientes).getDtNascimento());
                    v.add(null);
                } else if (clientes instanceof PessoaJuridica) {
                    v.add(null);
                    v.add(((PessoaJuridica) clientes).getDescontoLocacao());
                }

                modelo.addRow(v);
            }

            tblClientes.repaint();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this,
                    "Não foi possível carregar o novo cliente.\n\n" + ex.getMessage(),
                    "Erro",
                    JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterarCarro1;
    private javax.swing.JButton btnAlterarCliente;
    private javax.swing.JButton btnBuscarCarro;
    private javax.swing.JButton btnExcluirCarro2;
    private javax.swing.JButton btnExcluirCliente;
    private javax.swing.JButton btnLimparBuscarCarro;
    private javax.swing.JButton btnNovoCarro;
    private javax.swing.JButton btnNovoCliente;
    private javax.swing.JMenuItem btnSairArquivo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tblCarros;
    private javax.swing.JTable tblClientes;
    private javax.swing.JTextField txtBuscarCarro;
    // End of variables declaration//GEN-END:variables
}
